Repository team-pravo/pravo-server, pull requests merged in 2024-10, with the labels that each got.

#7 [CHORE] CI/CD 구축 과정
  .github/workflows/CD.yaml
  .github/workflows/CI.yaml
  .gitignore
  Dockerfile
  build.gradle.kts
  src/main/kotlin/com/pravo/pravo/domain/member/controller/MemberController.java
  src/main/kotlin/com/pravo/pravo/domain/member/model/Member.java
  src/main/kotlin/com/pravo/pravo/domain/member/repository/MemberRepository.java
  src/main/kotlin/com/pravo/pravo/domain/member/service/MemberService.java
  src/main/kotlin/com/pravo/pravo/global/auth/CustomAuthenticationEntryPoint.java
  src/main/kotlin/com/pravo/pravo/global/auth/controller/AuthController.java
  src/main/kotlin/com/pravo/pravo/global/auth/domain/UserDetailsCustom.java
  src/main/kotlin/com/pravo/pravo/global/auth/dto/LoginDTO.java
  src/main/kotlin/com/pravo/pravo/global/auth/dto/ResAccessTokenLoginDTO.java
  src/main/kotlin/com/pravo/pravo/global/security/config/SecurityConfiguration.java
  src/main/kotlin/com/pravo/pravo/global/security/util/SecurityUtil.java
  src/main/kotlin/com/pravo/pravo/global/util/FormatRestResponse.java
  src/main/kotlin/com/pravo/pravo/global/util/RestResponse.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-local.yaml
  src/main/resources/application.properties
  src/main/resources/application.yaml
  src/test/kotlin/com/pravo/pravo/PravoApplicationTests.kt
Labels: ✅ Done, ✨ Feature, ⚙️ Setting

#12 [FEAT] jwt 토큰 parse filter 추가
  build.gradle.kts
  src/main/kotlin/com/pravo/pravo/domain/member/dto/Member 관련 dto
  src/main/kotlin/com/pravo/pravo/global/auth/dto/LoginDTO.java
  src/main/kotlin/com/pravo/pravo/global/auth/dto/ResAccessTokenLoginDTO.java
  src/main/kotlin/com/pravo/pravo/global/jwt/AuthenticateUser.java
  src/main/kotlin/com/pravo/pravo/global/jwt/FilterConfig.java
  src/main/kotlin/com/pravo/pravo/global/jwt/JwtAuthorizationFilter.java
  src/main/kotlin/com/pravo/pravo/global/jwt/JwtTokenProvider.java
  src/main/kotlin/com/pravo/pravo/global/jwt/JwtTokens.java
  src/main/kotlin/com/pravo/pravo/global/jwt/JwtTokensGenerator.java
  src/main/kotlin/com/pravo/pravo/global/util/FormatRestResponse.java
  src/main/kotlin/com/pravo/pravo/global/util/RestResponse.java
  src/main/resources/application-local.yaml
Labels: ✅ Done, ✨ Feature

#5 [FEAT] 약속 목록 조회 기능 추가
  .gitignore
  build.gradle.kts
  lombok.config
  src/main/kotlin/com/pravo/pravo/domain/member/controller/MemberController.java
  src/main/kotlin/com/pravo/pravo/domain/member/dto/Member 관련 dto
  src/main/kotlin/com/pravo/pravo/domain/member/model/Member.java
  src/main/kotlin/com/pravo/pravo/domain/member/repository/MemberRepository.java
  src/main/kotlin/com/pravo/pravo/domain/member/service/MemberService.java
  src/main/kotlin/com/pravo/pravo/domain/promise/controller/PromiseController.kt
  src/main/kotlin/com/pravo/pravo/domain/promise/dto/request/PromiseCreateDto.kt
  src/main/kotlin/com/pravo/pravo/domain/promise/dto/request/PromiseSearchDto.kt
  src/main/kotlin/com/pravo/pravo/domain/promise/dto/response/PromiseResponseDto.kt
  src/main/kotlin/com/pravo/pravo/domain/promise/model/Promise.java
  src/main/kotlin/com/pravo/pravo/domain/promise/model/PromiseRole.java
  src/main/kotlin/com/pravo/pravo/domain/promise/model/enums/ParticipantStatus.java
  src/main/kotlin/com/pravo/pravo/domain/promise/model/enums/PromiseStatus.java
  src/main/kotlin/com/pravo/pravo/domain/promise/model/enums/RoleStatus.java
  src/main/kotlin/com/pravo/pravo/domain/promise/repository/PromiseRepository.java
  src/main/kotlin/com/pravo/pravo/domain/promise/repository/PromiseRepositoryCustom.java
  src/main/kotlin/com/pravo/pravo/domain/promise/repository/PromiseRepositoryImpl.java
  src/main/kotlin/com/pravo/pravo/domain/promise/service/PromiseService.kt
  src/main/kotlin/com/pravo/pravo/global/auth/dto/LoginDTO.java
  src/main/kotlin/com/pravo/pravo/global/auth/dto/ResAccessTokenLoginDTO.java
  src/main/kotlin/com/pravo/pravo/global/common/model/BaseTimeEntity.java
  src/main/kotlin/com/pravo/pravo/global/util/FormatRestResponse.java
  src/main/kotlin/com/pravo/pravo/global/util/RestResponse.java
  src/main/resources/application.properties
Labels: ✅ Done, ✨ Feature

#16 [DELETE] Unused DTO
  src/main/kotlin/com/pravo/pravo/global/auth/dto/LoginDTO.java
  src/main/kotlin/com/pravo/pravo/global/auth/dto/ResAccessTokenLoginDTO.java
Labels: ✅ Done

#18 [FEAT] global exception 추가
  src/main/kotlin/com/pravo/pravo/domain/member/service/MemberService.java
  src/main/kotlin/com/pravo/pravo/domain/promise/controller/PromiseController.kt
  src/main/kotlin/com/pravo/pravo/domain/promise/service/PromiseService.kt
  src/main/kotlin/com/pravo/pravo/global/common/error/ErrorCode.kt
  src/main/kotlin/com/pravo/pravo/global/common/error/ErrorResponse.kt
  src/main/kotlin/com/pravo/pravo/global/common/error/GlobalExceptionHandler.kt
  src/main/kotlin/com/pravo/pravo/global/common/error/exception/BaseException.java
  src/main/kotlin/com/pravo/pravo/global/common/error/exception/UnauthorizedException.java
Labels: ✅ Done, ✨ Feature, ⚙️ Setting
