Repository team-pravo/pravo-server, pull requests merged in 2024-12, with the labels that each got.

#71 [FEAT] 멤버 결제 내역 + 포인트 적립/사용 내역 조회
  src/main/kotlin/com/pravo/pravo/domain/fine/model/FineLog.java
  src/main/kotlin/com/pravo/pravo/domain/fine/repository/FineLogRepository.java
  src/main/kotlin/com/pravo/pravo/domain/fine/repository/FineLogRepository.kt
  src/main/kotlin/com/pravo/pravo/domain/member/controller/MemberApi.java
  src/main/kotlin/com/pravo/pravo/domain/member/controller/MemberController.java
  src/main/kotlin/com/pravo/pravo/domain/member/dto/MemberFineLogResponseDTO.java
  src/main/kotlin/com/pravo/pravo/domain/member/dto/MemberPaymentLogResponseDTO.java
  src/main/kotlin/com/pravo/pravo/domain/member/dto/MemberPointLogResponseDTO.java
  src/main/kotlin/com/pravo/pravo/domain/member/service/MemberService.java
  src/main/kotlin/com/pravo/pravo/domain/payment/model/PaymentLog.java
  src/main/kotlin/com/pravo/pravo/domain/payment/repository/PaymentLogRepository.java
  src/main/kotlin/com/pravo/pravo/domain/point/model/PointLog.java
  src/main/kotlin/com/pravo/pravo/domain/point/repository/PointLogRepository.java
  src/main/kotlin/com/pravo/pravo/domain/point/repository/PointLogRepository.kt
Labels: ✅ Done, ✨ Feature

#86 [HOTFIX] fcm config error
  src/main/kotlin/com/pravo/pravo/global/config/FirebaseConfig.java
Labels: 🐞 BugFix, ✅ Done

#92 [FIX] 결제 내역 조회
  src/main/kotlin/com/pravo/pravo/domain/member/service/MemberService.java
  src/main/kotlin/com/pravo/pravo/domain/payment/repository/PaymentLogRepository.java
Labels: ✅ Done
