Repository team-pravo/pravo-server, pull requests merged in 2024-11, with the labels that each got.

#17 [FEAT] add member login
  .gitignore
  build.gradle.kts
  src/main/kotlin/com/pravo/pravo/domain/member/controller/MemberController.java
  src/main/kotlin/com/pravo/pravo/domain/member/dto/LoginRequestDTO.java
  src/main/kotlin/com/pravo/pravo/domain/member/dto/LoginResponseDTO.java
  src/main/kotlin/com/pravo/pravo/domain/member/model/Member.java
  src/main/kotlin/com/pravo/pravo/domain/member/repository/MemberRepository.java
  src/main/kotlin/com/pravo/pravo/domain/member/resources/adjective.txt
  src/main/kotlin/com/pravo/pravo/domain/member/resources/noun.txt
  src/main/kotlin/com/pravo/pravo/domain/member/service/MemberService.java
  src/main/kotlin/com/pravo/pravo/domain/member/service/RandomNameGenerator.java
  src/main/kotlin/com/pravo/pravo/domain/promise/controller/PromiseApi.kt
  src/main/kotlin/com/pravo/pravo/domain/promise/controller/PromiseController.kt
  src/main/kotlin/com/pravo/pravo/global/auth/annotation/AuthUser.kt
  src/main/kotlin/com/pravo/pravo/global/auth/resolver/AuthUserArgumentResolver.java
  src/main/kotlin/com/pravo/pravo/global/common/ApiResponseDto.kt
  src/main/kotlin/com/pravo/pravo/global/common/error/ErrorResponse.kt
  src/main/kotlin/com/pravo/pravo/global/common/error/GlobalExceptionHandler.kt
  src/main/kotlin/com/pravo/pravo/global/config/RedisRepositoryConfig.java
  src/main/kotlin/com/pravo/pravo/global/config/SwaggerConfig.kt
  src/main/kotlin/com/pravo/pravo/global/config/WebMvcConfig.java
  src/main/kotlin/com/pravo/pravo/global/jwt/AuthenticateUser.java
  src/main/kotlin/com/pravo/pravo/global/jwt/FilterConfig.java
  src/main/kotlin/com/pravo/pravo/global/jwt/JwtAuthorizationFilter.java
  src/main/kotlin/com/pravo/pravo/global/jwt/JwtTokenProvider.java
  src/main/kotlin/com/pravo/pravo/global/jwt/JwtTokens.java
  src/main/kotlin/com/pravo/pravo/global/jwt/JwtTokensGenerator.java
  src/main/kotlin/com/pravo/pravo/global/oauth/kakao/dto/KakaoLoginRequestDTO.java
  src/main/kotlin/com/pravo/pravo/global/oauth/kakao/service/KakaoService.java
  src/main/resources/application-local.yaml
  src/main/resources/application-secret.properties.example
Labels: ✅ Done, ✨ Feature

#20 [FEAT] 약속 상세 조회
  .gitignore
  src/main/kotlin/com/pravo/pravo/domain/promise/controller/PromiseApi.kt
  src/main/kotlin/com/pravo/pravo/domain/promise/controller/PromiseController.kt
  src/main/kotlin/com/pravo/pravo/domain/promise/dto/response/ParticipantResponseDto.kt
  src/main/kotlin/com/pravo/pravo/domain/promise/dto/response/PromiseDetailResponseDto.kt
  src/main/kotlin/com/pravo/pravo/domain/promise/dto/response/PromiseResponseDto.kt
  src/main/kotlin/com/pravo/pravo/domain/promise/model/Promise.java
  src/main/kotlin/com/pravo/pravo/domain/promise/model/enums/PromiseStatus.java
  src/main/kotlin/com/pravo/pravo/domain/promise/repository/PromiseRepository.java
  src/main/kotlin/com/pravo/pravo/domain/promise/repository/PromiseRepositoryCustom.java
  src/main/kotlin/com/pravo/pravo/domain/promise/repository/PromiseRepositoryImpl.java
  src/main/kotlin/com/pravo/pravo/domain/promise/repository/PromiseRoleRepository.java
  src/main/kotlin/com/pravo/pravo/domain/promise/service/PromiseService.kt
  src/main/kotlin/com/pravo/pravo/global/auth/resolver/AuthUserArgumentResolver.java
  src/main/kotlin/com/pravo/pravo/global/common/error/exception/BaseException.java
  src/main/kotlin/com/pravo/pravo/global/common/error/exception/NotFoundException.java
  src/main/kotlin/com/pravo/pravo/global/common/error/exception/UnauthorizedException.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-local.yaml
Labels: ✅ Done, ✨ Feature

#27 [REFACTOR] Add api prefix in MemberController
  src/main/kotlin/com/pravo/pravo/domain/member/controller/MemberController.java
  src/main/kotlin/com/pravo/pravo/global/jwt/JwtAuthorizationFilter.java
Labels: ✅ Done

#31 [FEAT] apple login
  src/main/kotlin/com/pravo/pravo/domain/member/controller/MemberController.java
  src/main/kotlin/com/pravo/pravo/domain/member/dto/LoginResponseDTO.java
  src/main/kotlin/com/pravo/pravo/domain/member/model/Member.java
  src/main/kotlin/com/pravo/pravo/domain/member/service/MemberService.java
  src/main/kotlin/com/pravo/pravo/domain/promise/dto/response/ParticipantResponseDto.kt
  src/main/kotlin/com/pravo/pravo/domain/promise/repository/PromiseRepositoryImpl.java
  src/main/kotlin/com/pravo/pravo/global/oauth/apple/AppleIdentityTokenVerifier.java
  src/main/kotlin/com/pravo/pravo/global/oauth/apple/service/AppleService.java
  src/main/kotlin/com/pravo/pravo/global/oauth/domain/SocialLoginRequestToken.java
  src/main/kotlin/com/pravo/pravo/global/oauth/domain/enums/SocialProvider.java
  src/main/kotlin/com/pravo/pravo/global/oauth/kakao/dto/KakaoLoginRequestDTO.java
  src/main/resources/application-local.yaml
Labels: ✅ Done, ✨ Feature

#44 [FEAT] S3 모듈 제작
  build.gradle.kts
  src/main/kotlin/com/pravo/pravo/global/common/error/ErrorCode.kt
  src/main/kotlin/com/pravo/pravo/global/config/S3Config.kt
  src/main/kotlin/com/pravo/pravo/global/external/s3/S3Controller.kt
  src/main/kotlin/com/pravo/pravo/global/external/s3/S3Service.kt
  src/main/resources/application.yaml
Labels: ✅ Done, ✨ Feature, ⚙️ Setting

#30 [FEAT] 토스 페이먼츠 결제 모듈 개발
  build.gradle.kts
  src/main/kotlin/com/pravo/pravo/PravoApplication.kt
  src/main/kotlin/com/pravo/pravo/domain/member/service/MemberService.java
  src/main/kotlin/com/pravo/pravo/domain/payment/controller/PaymentApi.kt
  src/main/kotlin/com/pravo/pravo/domain/payment/controller/PaymentController.kt
  src/main/kotlin/com/pravo/pravo/domain/payment/dto/response/RequestOrderResponseDto.kt
  src/main/kotlin/com/pravo/pravo/domain/payment/enums/PaymentStatus.kt
  src/main/kotlin/com/pravo/pravo/domain/payment/model/Card.java
  src/main/kotlin/com/pravo/pravo/domain/payment/model/EasyPay.java
  src/main/kotlin/com/pravo/pravo/domain/payment/model/PaymentLog.java
  src/main/kotlin/com/pravo/pravo/domain/payment/repository/CardRepository.kt
  src/main/kotlin/com/pravo/pravo/domain/payment/repository/EasyPayRepository.kt
  src/main/kotlin/com/pravo/pravo/domain/payment/repository/PaymentLogRepository.kt
  src/main/kotlin/com/pravo/pravo/domain/payment/service/PaymentFacade.kt
  src/main/kotlin/com/pravo/pravo/domain/payment/service/PaymentService.kt
  src/main/kotlin/com/pravo/pravo/domain/promise/controller/PromiseApi.kt
  src/main/kotlin/com/pravo/pravo/domain/promise/controller/PromiseController.kt
  src/main/kotlin/com/pravo/pravo/domain/promise/dto/request/PromiseCreateDto.kt
  src/main/kotlin/com/pravo/pravo/domain/promise/model/Promise.java
  src/main/kotlin/com/pravo/pravo/domain/promise/service/PromiseService.kt
  src/main/kotlin/com/pravo/pravo/global/auth/resolver/AuthUserArgumentResolver.java
  src/main/kotlin/com/pravo/pravo/global/common/ApiResponseDto.kt
  src/main/kotlin/com/pravo/pravo/global/error/ErrorCode.kt
  src/main/kotlin/com/pravo/pravo/global/error/GlobalExceptionHandler.kt
  src/main/kotlin/com/pravo/pravo/global/error/exception/BaseException.java
  src/main/kotlin/com/pravo/pravo/global/error/exception/NotFoundException.java
  src/main/kotlin/com/pravo/pravo/global/error/exception/UnauthorizedException.java
  src/main/kotlin/com/pravo/pravo/global/external/s3/S3Service.kt
  src/main/kotlin/com/pravo/pravo/global/external/toss/PaymentClient.kt
  src/main/kotlin/com/pravo/pravo/global/external/toss/dto/request/ConfirmRequestDto.kt
  src/main/kotlin/com/pravo/pravo/global/external/toss/dto/response/CancelDto.kt
  src/main/kotlin/com/pravo/pravo/global/external/toss/dto/response/CardDto.kt
  src/main/kotlin/com/pravo/pravo/global/external/toss/dto/response/CashReceiptDto.kt
  src/main/kotlin/com/pravo/pravo/global/external/toss/dto/response/CashReceiptHistoryDto.kt
  src/main/kotlin/com/pravo/pravo/global/external/toss/dto/response/ConfirmResponseDto.kt
  src/main/kotlin/com/pravo/pravo/global/external/toss/dto/response/EasyPayDto.kt
  src/main/kotlin/com/pravo/pravo/global/external/toss/dto/response/FailureDto.kt
  src/main/kotlin/com/pravo/pravo/global/external/toss/dto/response/VirtualAccountDto.kt
  src/main/kotlin/com/pravo/pravo/global/util/CommonLogger.kt
  src/main/resources/application-local.yaml
  src/main/resources/application.yaml
Labels: ✅ Done, ✨ Feature

#42 [FEAT] 마이페이지 화면 조회
  src/main/kotlin/com/pravo/pravo/domain/member/controller/MemberApi.java
  src/main/kotlin/com/pravo/pravo/domain/member/controller/MemberController.java
  src/main/kotlin/com/pravo/pravo/domain/member/dto/MyPageResponseDTO.java
  src/main/kotlin/com/pravo/pravo/domain/member/model/Member.java
  src/main/kotlin/com/pravo/pravo/domain/member/repository/MemberRepository.java
  src/main/kotlin/com/pravo/pravo/domain/member/service/MemberService.java
  src/main/kotlin/com/pravo/pravo/global/oauth/controller/AuthController.java
Labels: ✅ Done, ✨ Feature

#37 [FEAT] delete promise API
  src/main/kotlin/com/pravo/pravo/PravoApplication.kt
  src/main/kotlin/com/pravo/pravo/domain/promise/controller/PromiseApi.kt
  src/main/kotlin/com/pravo/pravo/domain/promise/controller/PromiseController.kt
  src/main/kotlin/com/pravo/pravo/domain/promise/model/Promise.java
  src/main/kotlin/com/pravo/pravo/domain/promise/model/PromiseRole.java
  src/main/kotlin/com/pravo/pravo/domain/promise/repository/PromiseRepository.java
  src/main/kotlin/com/pravo/pravo/domain/promise/repository/PromiseRepositoryImpl.java
  src/main/kotlin/com/pravo/pravo/domain/promise/repository/PromiseRoleRepository.java
  src/main/kotlin/com/pravo/pravo/domain/promise/service/PromiseRoleService.kt
  src/main/kotlin/com/pravo/pravo/domain/promise/service/PromiseService.kt
  src/main/kotlin/com/pravo/pravo/global/error/GlobalExceptionHandler.kt
  src/main/kotlin/com/pravo/pravo/global/error/exception/BaseException.java
  src/main/resources/application-local.yaml
Labels: ✅ Done, ✨ Feature

#57 [FEAT] 닉네임 및 프로필 설정 + Logout 수정
  src/main/kotlin/com/pravo/pravo/domain/member/controller/MemberApi.java
  src/main/kotlin/com/pravo/pravo/domain/member/controller/MemberController.java
  src/main/kotlin/com/pravo/pravo/domain/member/dto/ProfileChangeRequestDTO.java
  src/main/kotlin/com/pravo/pravo/domain/member/model/Member.java
  src/main/kotlin/com/pravo/pravo/domain/member/service/MemberService.java
  src/main/kotlin/com/pravo/pravo/global/error/ErrorCode.kt
  src/main/kotlin/com/pravo/pravo/global/external/s3/S3Service.kt
  src/main/kotlin/com/pravo/pravo/global/jwt/JwtAuthorizationFilter.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-local.yaml
Labels: ✅ Done, ✨ Feature

#55 [FEAT] 결제 취소 로직 구현
  src/main/kotlin/com/pravo/pravo/domain/payment/model/PaymentLog.java
  src/main/kotlin/com/pravo/pravo/domain/payment/repository/PaymentLogRepository.java
  src/main/kotlin/com/pravo/pravo/domain/payment/repository/PaymentLogRepository.kt
  src/main/kotlin/com/pravo/pravo/domain/payment/service/PaymentFacade.kt
  src/main/kotlin/com/pravo/pravo/domain/payment/service/PaymentService.kt
  src/main/kotlin/com/pravo/pravo/global/external/toss/PaymentClient.kt
  src/main/kotlin/com/pravo/pravo/global/external/toss/dto/request/CancelRequestDto.kt
  src/main/kotlin/com/pravo/pravo/global/external/toss/dto/response/TossResponseDto.kt
  src/main/resources/application.yaml
Labels: ✅ Done, ✨ Feature

#63 [FEAT] 약속 정산 관련 도메인 생성
  src/main/kotlin/com/pravo/pravo/domain/fine/model/FineLog.java
  src/main/kotlin/com/pravo/pravo/domain/fine/repository/FineLogRepository.kt
  src/main/kotlin/com/pravo/pravo/domain/fine/service/FineLogService.kt
  src/main/kotlin/com/pravo/pravo/domain/member/model/Member.java
  src/main/kotlin/com/pravo/pravo/domain/point/model/PointLog.java
  src/main/kotlin/com/pravo/pravo/domain/point/model/PointLogStatus.java
  src/main/kotlin/com/pravo/pravo/domain/point/repository/PointLogRepository.kt
  src/main/kotlin/com/pravo/pravo/domain/point/service/PointLogService.kt
Labels: ✅ Done, ✨ Feature

#66 [FEAT] 참가자 결제 요청 API 구현
  src/main/kotlin/com/pravo/pravo/domain/payment/controller/PaymentApi.kt
  src/main/kotlin/com/pravo/pravo/domain/payment/controller/PaymentController.kt
  src/main/kotlin/com/pravo/pravo/domain/payment/service/PaymentFacade.kt
Labels: ✅ Done, ✨ Feature
